### ISSUE TITLE
"replace"  issue

### ISSUE THREAD

**Issue by acaramia** [uwol/cobol85grammar#1]
Hi, 
I have an issue with the `replace `method of `Cobol85PreprocessorImpl `class. 
The problem could happen when there are two identifiers in `currentReplaceableReplacements `whose name is a substring of each other. Example:
```
REPLACE
==TEST1== by =='VAL1'==
==TEST1-SECOND-PART== by =='VAL2'==
```

Depending on the order of substitution, you could have this kind of results 
`'VAL1'-SECOND-PART ` instead of `'VAL2'` when processing `TEST1-SECOND-PART`
I'll try to order the substitution (sort on lenght of tokens and process the longest first)
Thanks

**Comment by uwol** [comment]
Hi @acaramia,
yes, please feel free to make a pull request. Currently, I am making refinements to the grammar. So, if you are missing features or find bugs, let me know.

Thanks, 
Ulrich

**Comment by uwol** [comment]
merged pull request
